openapi: 3.0.0
info:
    title: Nodejs Upskillfest Boilerplate
    description: Node JS Express API
    version: 1.0.0
servers:
    - url: http://localhost:5000/api/v1
      description: Local Server
    - url: http://staging-api.example.com
      description: Internal staging server for testing
paths:
    /users:
        get:
            summary: Returns a list of users.
            description: GET all Users
            responses:
                '200': # status code
                    description: A JSON array of user names
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    success:
                                        type: boolean
                                    data:
                                        type: array
                                        items:
                                            # - ref:
                                            #       './definitions/get-users.yaml'
                                            type: object
                                    totalCount:
                                        type: number
